### ISSUE TITLE
Does not install on osx out of the box

### ISSUE THREAD

**Issue by morenoh149** [ethereumjs/helpeth#25]
I seem to be running into a python issue when attempting to install this globally
```
$ npm install -g helpeth
        
> scrypt@6.0.3 preinstall /usr/local/lib/node_modules/helpeth/node_modules/scrypt
> node node-scrypt-preinstall.js                                                     
                                                 
/usr/local/bin/helpeth -> /usr/local/lib/node_modules/helpeth/helpeth
                                                                       
> keccak@1.4.0 install /usr/local/lib/node_modules/helpeth/node_modules/keccak
> npm run rebuild || echo "Keccak bindings compilation fail. Pure JS implementation w
ill be used." 
                                                                              
                                                          
> keccak@1.4.0 rebuild /usr/local/lib/node_modules/helpeth/node_modules/keccak
> node-gyp rebuild                                                              
                                                                                     
gyp ERR! configure error
gyp ERR! stack Error: Command failed: /usr/local/opt/python/libexec/bin/python -c imp
ort sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:294:12)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:978:16)
gyp ERR! stack     at Socket.stream.socket.on (internal/child_process.js:395:11)
gyp ERR! stack     at Socket.emit (events.js:189:13)
gyp ERR! stack     at Pipe._handle.close (net.js:613:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/usr/local/Cellar/node/11.4.0/bin/node" "/usr/local/lib/node_module
s/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/helpeth/node_modules/keccak
gyp ERR! node -v v11.4.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! keccak@1.4.0 rebuild: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the keccak@1.4.0 rebuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging
output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/harrymoreno/.npm/_logs/2018-12-18T22_47_46_030Z-debug.log
Keccak bindings compilation fail. Pure JS implementation will be used.

> scrypt@6.0.3 install /usr/local/lib/node_modules/helpeth/node_modules/scrypt
```
perhaps an issue with the Keccak dependency?

python -V returns 3.7.1

**Comment by cclauss** [comment]
What does __python2 -V__ return because __node__ currently requires _legacy_ Python.

**Comment by morenoh149** [comment]
nothing, I ran this on the newest MacBook. And it no longer ships with python2.

Attn: maintainers, if this issue is beyond the scope of helpeth please close it. I see now this is a larger issue with the node ecosystem depending on python2 for building dependencies.

**Comment by cclauss** [comment]
From above: __/usr/local/opt/python/libexec/bin/python__ looks like where homebrew would put Python.

Try $ __/usr/bin/python -V__ to see what the Apple "system" Python is.  I _dobut_ that will be Python 3.

**Comment by morenoh149** [comment]
@cclauss oh that prints 2.7.10
